### ISSUE TITLE
Reproducibility Issue

### ISSUE THREAD

**Issue by fmenegui** [Sakib1263/NABNet#1]
I have been trying to reproduce the results from your paper using the code that you have provided in this repo, but I was not able to achieve similar results.

Specifically, I have been trying to run the jupyter notebook "PPG-ECG-to-BP-Prediction-ABP-Estimation/Codes/Deep Learning Pipeline/PPG_ECG_to_BP_Prediction_Pipeline.ipynb" to reproduce the results. I have also used the dataset that you provided in "PPG-ECG-to-BP-Prediction-ABP-Estimation/Datasets/". My results, however, are **very different**:
![image(1)](https://user-images.githubusercontent.com/17231485/170129419-06f6a62e-2b43-4a3e-b23a-1e16b6af6e35.png)

What should I do in order to obtain the same results that you obtained in your paper ?

Thank you.

**Comment by lirus7** [comment]
Hey!
Can you tell me what's the standard deviation of the result you are observing coz I am having a similar issue?

**Comment by Huqy518** [comment]
Hey! 
I have the same result.
Have you solved it?
